/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./app/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
    presets: [require('nativewind/preset')],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: '#edfaf5',
                    100: '#d2f3e6',
                    200: '#a8e6cf',
                    300: '#6fd4b0',
                    400: '#3dbc92',
                    500: '#2D9B7F',
                    600: '#237d66',
                    700: '#1b6150',
                    800: '#154d40',
                    900: '#0f3830',
                },
                neutral: {
                    0: '#ffffff',
                    50: '#f8f8f8',
                    100: '#f0f0f0',
                    200: '#e0e0e0',
                    300: '#c4c4c4',
                    400: '#a0a0a0',
                    500: '#737373',
                    600: '#525252',
                    700: '#363636',
                    800: '#1f1f1f',
                    900: '#111111',
                },
                success: '#2D9B7F',
                warning: '#F59E0B',
                error: '#EF4444',
                info: '#3B82F6',
            },
            fontFamily: {
                title: ['DaysOne_400Regular'],
                sans: ['InstrumentSans_400Regular'],
                'sans-md': ['InstrumentSans_500Medium'],
                'sans-semi': ['InstrumentSans_600SemiBold'],
                'sans-bold': ['InstrumentSans_700Bold'],
            },

            fontSize: {
                xs: ['12px', { lineHeight: '16px' }],
                sm: ['14px', { lineHeight: '20px' }],
                base: ['16px', { lineHeight: '24px' }],
                lg: ['18px', { lineHeight: '28px' }],
                xl: ['20px', { lineHeight: '30px' }],
                '2xl': ['24px', { lineHeight: '32px' }],
                '3xl': ['30px', { lineHeight: '38px' }],
                '4xl': ['36px', { lineHeight: '44px' }],
                '5xl': ['48px', { lineHeight: '56px' }],
            },

            spacing: {
                px: '1px',
                0: '0px',
                0.5: '2px',
                1: '4px',
                1.5: '6px',
                2: '8px',
                2.5: '10px',
                3: '12px',
                4: '16px',
                5: '20px',
                6: '24px',
                8: '32px',
                10: '40px',
                12: '48px',
                16: '64px',
                20: '80px',
                24: '96px',
            },
            borderRadius: {
                none: '0px',
                sm: '6px',
                md: '12px',
                lg: '16px',
                xl: '20px',
                full: '9999px',
            },
        },
    },
    plugins: [],
}